[package]
name = "testauskoira-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["cache", "client", "gateway","standard_framework", "rustls_backend", "model","framework"]

[dependencies.tokio]
version = "1.12"
features = ["macros", "rt-multi-thread","signal"]

[dependencies.sqlx]
version = "0.5"
features = ["mysql","runtime-tokio-rustls","bigdecimal"]

[dependencies.imap]
version = "3.0.0-alpha.4"
default-features = false
features = ["rustls-tls","rustls-connector"]

[dependencies]
regex = {version = "1.5", features = ["default"]}
dotenv = "0.15"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
futures = "0.3"
num-traits = "0.2"
rand = "0.8"
photon-rs = "0.3"
rustls = "0.20" 
